# fly.toml app configuration file generated for groupventure-server on 2023-07-10T18:44:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "groupventure-server"
primary_region = "mad"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
